@bank-rut_HostAddress = http://localhost:8080

### 1) Каталог товаров
GET {{rut_shop.net_HostAddress}}/api/products
Accept: application/json

###

### 2) Список клиентов
GET {{rut_shop.net_HostAddress}}/api/customers
Accept: application/json

###

### 3) Создать покупку
POST {{rut_shop.net_HostAddress}}/api/purchases
Content-Type: application/json

{
  "customerId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1",
  "productIds": [
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1",
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2",
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"
  ]
}

###

### 4) Бонусный баланс клиента
GET {{rut_shop.net_HostAddress}}/api/customers/bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1/loyalty
Accept: application/json

###

### 5) Скачивание чека по покупке (подставьте ваш purchaseId)
GET {{rut_shop.net_HostAddress}}/api/purchases/{purchaseId}/receipt
